### PR TITLE
feat: add support for FHE decryption (for testing)

### PR DESCRIPTION
**Pull request by dartdart26**

### CODE REVIEW

**Comment by immortal-tofu** [comment]
Instead of exposing this decrypt function in the instance, I'd prefer you add it in src/tfhe.ts. Functions in `tfhe.ts` are already usable in node (for example, we're using `createTfheKeypair` for tests).

**Review by immortal-tofu — CHANGES_REQUESTED** [review]
Instead of exposing this decrypt function in the instance, I'd prefer you add it in src/tfhe.ts. Functions in tfhe.ts are already usable in node (for example, we're using createTfheKeypair for tests).

**Comment by dartdart26** [comment]
> Why did you rename `encrypt` to `tfheEncrypt`?

Just to make it symmetrical as we have decrypt for the classical one and tfheDecrypt for FHE.

**Comment by dartdart26** [comment]
> Instead of exposing this decrypt function in the instance, I'd prefer you add it in src/tfhe.ts. Functions in tfhe.ts are already usable in node (for example, we're using createTfheKeypair for tests).

Cool. Should I store the clientKey in the instance and users passing it to these functions in tfhe.ts?

**Comment by dartdart26** [comment]
Will open a new PR with a simpler implementation.

**Pull request closed without merging**
